# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('icmp_example', ['core'])
    module.source = [
        'model/icmp_example.cc',
        'model/icmp_example-type1.cc',
        'model/icmp_example-type0.cc',
        'helper/icmp_example-helper.cc',
        'model/icmp_example-PacketFactory.cc',
        'model/icmp_example-PacketType.cc',
        ]

    module_test = bld.create_ns3_module_test_library('icmp_example')
    module_test.source = [
        'test/icmp_example-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'icmp_example'
    headers.source = [
        'model/icmp_example.h',
        'model/icmp_example-type1.h',
        'model/icmp_example-type0.h',
        'model/icmp_example-Grammar.h',
        'helper/icmp_example-helper.h',
        'model/icmp_example-PacketFactory.h',
        'model/icmp_example-PacketType.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')
    # bld.ns3_python_bindings()